use hero_icons::prelude::*;
use yew::prelude::*;

#[function_component(Demos)]
pub fn demos() -> Html {
    html! {
        <>
        <div class="grid grid-cols-9 gap-4">
                <ArrowCircleLeftOutLined />
                <ArrowCircleRightOutLined />
                <ArrowDownOutLined />
                <ArrowLeftOutLined />
                <ArrowNarrowLeftOutLined />
                <ArrowNarrowRightOutLined />
                <AdjustmentsIconOutLined />
                <ArrowRightOutLined />
                <ArrowSmDownOutLined />
                <ArrowSmLeftOutLined />
                <ArrowSmRightOutLined />
                <ArrowSmUpOutLined />
                <ArrowExpandOutLined />
                <AtSymbolOutLined />
                <BackspaceOutLined />
                <BadgeCheckOutLined />
                <BanOutLined />
                <BeakerOutLined />
                <BellOutLined />
                <BookOpenOutLined />
                <BookmarkAltOutLined />
                <BookmarkOutLined />
                <BriefcaseOutLined />
                <AcademicCapOutLined />
                <AnnotationOutLined />
                <ArrowLeftIconOutLined />
                <ArrowNarrowDownOutLined />
                <ArchiveOutLined />
                <ArrowNarrowUpOutLined />
                <ArrowUpOutLined />
                <ArrowCircleUpOutLined />
                <CheckOutLined />
                <ChevronDownOutLined />
                <ChevronLeftOutLined />
                <ChevronRightOutLined />
                <ChevronUpOutLined />
                <PlusOutLined />
                <PlusCircleOutLined />
                <PlusSmOutLined />
                <PresentationCharBarOutLined />
                <PresentationChartLineOutLined />
                <PrinterOutLined />
                <PuzzleOutLined />
                <QrcodeOutLined />
                <QuestionMarkCircleOutLined />
                <ReceiptRefundOutLined />
                <ReceiptTaxOutLined />
                <RefreshOutLined />
                <ReplyOutLined />
                <RewindOutLined />
                <RssOutLined />
                <SaveAsOutLined />
                <SaveOutLined />
                <ScaleOutLined />
                <ScissorsOutLined />
                <SearchCircleOutLined />
                <SearchOutLined />
                <SelectorOutLined />
                <ServerOutLined />
                <ShareOutLined />
                <ShieldCheckOutLined />
                <ShieldExclamationOutLined />
                <ShoppingBagOutLined />
                <ShoppingCartOutLined />
                <SortAscendingOutLined />
                <SortDescendingOutLined />
                <SparklesOutLined />
                <SpeakerPhoneOutLined />
                <StarOutLined />
                <StatusOfflineOutLined />
                <StatusOnlineOutLined />
                <StopOutLined />
                <SunOutLined />
                <SupportOutLined />
                <SwitchHorizontalOutLined />
                <SwitchVerticalOutLined />
                <TableOutLined />
                <TagOutLined />
                <TemplateOutLined />
                <TerminalOutLined />
                <ThumbDownOutLined />
                <ThumbUpOutLined />
                <TicketOutLined />
                <TranslateOutLined />
                <TrashOutLined />
                <TrendingUpOutLined />
                <TruckOutLined />
                <UploadOutLined />
                <UserAddOutLined />
                <UserCircleOutLined />
                <UserGroupOutLined />
                <UserRemoveOutLined />
                <UserOutLined />
                <UsersOutLined />
                <VariableOutLined />
                <VideoCameraOutLined />
                <ViewBoardsOutLined />
                <ViewGridAddOutLined />
                <ViewGridOutLined />
                <ViewListOutLined />
                <VolumeOffOutLined />
                <VolumeUpOutLined />
                <WifiOutLined />
                <XCircleOutLined />
                <XOutLined />
                <ZoomInOutLined />
                <ZoomOutOutLined />
                <CakeOutLined />
                <CalculatorOutLined />
                <CalendarOutLined />
                <CameraOutLined />
                <CashOutLined />
                <ChartBarOutLined />
                <ChartPieOutLined />
                <ChartSquareBarOutLined />
                <ChatAlt2OutLined />
                <ChatOutLined />
                <CheckCircleOutLined />
                <ChevronDoubleDownOutLined />
                <ChevronDoubleLeftOutLined />
                <ChevronDoubleRightOutLined />
                <ChevronDoubleUpOutLined />
                <CloudUploadOutLined />
                <CloudDownloadOutLined />
                <ClockOutLined />
                <ClipboardOutLined />
                <ChipOutLined />
                <ClipboardCheckOutLined />
                <ClipboardCopyOutLined />
                <ClipboardListOutLined />
                <CloudOutLined />
                <CodeOutLined />
                <CogOutLined />
                <CollectionOutLined />
                <ColorSwatchOutLined />
                <CreditCardOutLined />
                <CubeTransparentOutLined />
                <CubeOutLined />
                <CurrencyBangladeshiOutLined />
                <CurrencyDollarOutLined />
                <CurrencyEuroOutLined />
                <CurrencyPoundOutLined />
                <CurrencyRupeeOutLined />
                <CurrencyYenOutLined />
                <CursorClickOutLined />
                <DatabaseOutLined />
                <DesktopComputerOutLined />
                <DeviceMobileOutLined />
                <DeviceTabletOutLined />
                <DocumentAddOutLined />
                <DocumentDownloadOutLined />
                <DocumentDuplicateOutLined />
                <DocumentRemoveOutLined />
                <DocumentReportOutLined />
                <DocumentSearchOutLined />
                <DocumentTextOutLined />
                <DocumentOutLined />
                <DotsCircleHorizontalOutLined />
                <DotsHorizontalOutLined />
                <DotsVerticalOutLined />
                <DownloadOutLined />
                <DuplicateOutLined />
                <EmojiHappyOutLined />
                <EmojiSadOutLined />
                <ExclamationCircleOutLined />
                <ExclamationOutLined />
                <ExternalLinkOutLined />
                <EyeOffOutLined />
                <EyeOutLined />
                <FastForwardOutLined />
                <FilmOutLined />
                <FilterOutLined />
                <FingerPrintOutLined />
                <FireOutLined />
                <FlagOutLined />
                <FolderAddOutLined />
                <FolderDownloadOutLined />
                <FolderOpenOutLined />
                <FolderRemoveOutLined />
                <FolderOutLined />
                <GiftOutLined />
                <GlobeAltOutLined />
                <GlobeOutLined />
                <HandOutLined />
                <HashtagOutLined />
                <HeartOutLined />
                <HomeOutLined />
                <IdentificationOutLined />
                <InboxInOutLined />
                <InboxOutLined />
                <InformationCircleOutLined />
                <KeyOutLined />
                <LibraryOutLined />
                <LightBulbOutLined />
                <LightningBoltOutLined />
                <LinkOutLined />
                <LocationMarkerOutLined />
                <LockClosedOutLined />
                <LockOpenOutLined />
                <LoginOutLined />
                <LogoutOutLined />
                <MailOpenOutLined />
                <MailOutLined />
                <MapOutLined />
                <MenuAlt1OutLined />
                <MenuAlt2OutLined />
                <MenuAlt3OutLined />
                <MenuAlt4OutLined />
                <MenuOutLined />
                <MicrophoneOutLined />
                <MinusCircleOutLined />
                <MinusSmOutLined />
                <MinusOutLined />
                <MoonOutLined />
                <MusicNoteOutLined />
                <NewspaperOutLined />
                <OfficeBuildingOutLined />
                <PaperAirplaneOutLined />
                <PaperClipOutLined />
                <PauseOutLined />
                <PencilAltOutLined />
                <PencilOutLined />
                <PhoneIncomingOutLined />
                <PhoneMissedCallOutLined />
                <PhoneOutGoingOutLined />
                <PhoneOutLined />
                <PhotographOutLined />
                <PlayOutLined />




        </div>
         </>



    }
}
