use hero_icons::prelude::*;
use yew::prelude::*;

#[function_component(Demo)]
pub fn demo() -> Html {
    html! {
        <div class="grid grid-cols-9 gap-4">
            <ArrowNarrowRightIconSolid />
            <ArrowCircleLeftIconSolid />
            <ArrowCircleRightIconSolid />
            <ArrowDownIconSolid />
            <ArrowNarrowLeftIconSolid />
            <AdjustmentsIconSolid />
            <ArrowRightIconSolid />
            <ArrowSmDownIconSolid />
            <ArrowSmLeftIconSolid />
            <ArrowSmRightIconSolid />
            <ArrowSmUpIconSolid />
            <ArrowsExpandIconSolid />
            <AtSymbolIconSolid />
            <BackspaceIconSolid />
            <BadgeCheckIconSolid />
            <BanIconSolid />
            <BeakerIconSolid />
            <BellIconSolid />
            <BookOpenIconSolid />
            <BookmarkAltIconSolid />
            <BookmarkIconSolid />
            <BriefcaseIconSolid />
            <AcademicCapIconSolid />
            <AnnotationIconSolid />
            <ArrowLeftIconSolid />
            <ArrowNarrowDownIconSolid />
            <ArchiveIconSolid />
            <ArrowNarrowUpIconSolid />
            <ArrowUpIconSolid />
            <ArrowCircleUpIconSolid />
            <CheckIconSolid />
            <ChevronDownIconSolid />
            <ChevronLeftIconSolid />
            <ChevronRightIconSolid />
            <ChevronUpIconSolid />
            <PlusIconSolid />
            <PlusCircleIconSolid />
            <PlusSmIconSolid />
            <PresentationCharBarIconSolid />
            <PresentationChartLineIconSolid />
            <PrinterIconSolid />
            <PuzzleIconSolid />
            <QrcodeIconSolid />
            <QuestionMarkCircleIconSolid />
            <ReceiptRefundIconSolid />
            <ReceiptTaxIconSolid />
            <RefreshIconSolid />
            <ReplyIconSolid />
            <RewindIconSolid />
            <RssIconSolid />
            <SaveAsIconSolid />
            <SaveIconSolid />
            <ScaleIconSolid />
            <ScissorsIconSolid />
            <SearchCircleIconSolid />
            <SearchIconSolid />
            <SelectorIconSolid />
            <ServerIconSolid />
            <ShareIconSolid />
            <ShieldCheckIconSolid />
            <ShieldExclamationIconSolid />
            <ShoppingBagIconSolid />
            <ShoppingCartIconSolid />
            <SortAscendingIconSolid />
            <SortDescendingIconSolid />
            <SparklesIconSolid />
            <SpeakerPhoneIconSolid />
            <StarIconSolid />
            <StatusOfflineIconSolid />
            <StatusOnlineIconSolid />
            <StopIconSolid />
            <SunIconSolid />
            <SupportIconSolid />
            <SwitchHorizontalIconSolid />
            <SwitchVerticalIconSolid />
            <TableIconSolid />
            <TagIconSolid />
            <TemplateIconSolid />
            <TerminalIconSolid />
            <ThumbDownIconSolid />
            <ThumbUpIconSolid />
            <TicketIconSolid />
            <TranslateIconSolid />
            <TrashIconSolid />
            <TrendingUpIconSolid />
            <TruckIconSolid />
            <UploadIconSolid />
            <UserAddIconSolid />
            <UserCircleIconSolid />
            <UserGroupIconSolid />
            <UserRemoveIconSolid />
            <UserIconSolid />
            <UsersIconSolid />
            <VariableIconSolid />
            <VideoCameraIconSolid />
            <ViewBoardsIconSolid />
            <ViewGridAddIconSolid />
            <ViewGridIconSolid />
            <ViewListIconSolid />
            <VolumeOffIconSolid />
            <VolumeUpIconSolid />
            <WifiIconSolid />
            <XCircleIconSolid />
            <XIconSolid />
            <ZoomInIconSolid />
            <ZoomOutIconSolid />
            <CakeIconSolid />
            <CalculatorIconSolid />
            <CalendarIconSolid />
            <CameraIconSolid />
            <CashIconSolid />
            <ChartBarIconSolid />
            <ChartPieIconSolid />
            <ChartSquareBarIconSolid />
            <ChatAlt2IconSolid />
            <ChatIconSolid />
            <CheckCircleIconSolid />
            <ChevronDoubleDownIconSolid />
            <ChevronDoubleLeftIconSolid />
            <ChevronDoubleRightIconSolid />
            <ChevronDoubleUpIconSolid />
            <CloudUploadIconSolid />
            <CloudDownloadIconSolid />
            <ClockIconSolid />
            <ClipboardIconSolid />
            <ChipIconSolid />
            <ClipboardCheckIconSolid />
            <ClipboardCopyIconSolid />
            <ClipboardListIconSolid />
            <CloudIconSolid />
            <CodeIconSolid />
            <CogIconSolid />
            <CollectionIconSolid />
            <ColorSwatchIconSolid />
            <CreditCardIconSolid />
            <CubeTransparentIconSolid />
            <CubeIconSolid />
            <CurrencyBangladeshiIconSolid />
            <CurrencyDollarIconSolid />
            <CurrencyEuroIconSolid />
            <CurrencyPoundIconSolid />
            <CurrencyRupeeIconSolid />
            <CurrencyYenIconSolid />
            <CursorClickIconSolid />
            <DatabaseIconSolid />
            <DesktopComputerIconSolid />
            <DeviceMobileIconSolid />
            <DeviceTabletIconSolid />
            <DocumentAddIconSolid />
            <DocumentDownloadIconSolid />
            <DocumentDuplicateIconSolid />
            <DocumentRemoveIconSolid />
            <DocumentReportIconSolid />
            <DocumentSearchIconSolid />
            <DocumentTextIconSolid />
            <DocumentIconSolid />
            <DotsCircleHorizontalIconSolid />
            <DotsHorizontalIconSolid />
            <DotsVerticalIconSolid />
            <DownloadIconSolid />
            <DuplicateIconSolid />
            <EmojiHappyIconSolid />
            <EmojiSadIconSolid />
            <ExclamationCircleIconSolid />
            <ExclamationIconSolid />
            <ExternalLinkIconSolid />
            <EyeOffIconSolid />
            <EyeIconSolid />
            <FastForwardIconSolid />
            <FilmIconSolid />
            <FilterIconSolid />
            <FingerPrintIconSolid />
            <FireIconSolid />


        </div>
    }
}
