pub mod alert;
pub mod avatar;
pub mod badge;
pub mod button;
pub mod card;
pub mod carousel;
pub mod collapse;
pub mod display_helper;
pub mod drawer;
pub mod dropdown;
pub mod home;
pub mod indicator;
pub mod link;
pub mod menu;
pub mod modal;
pub mod nav;
pub mod select;
pub mod step;
pub mod tab;
pub mod table;
pub mod text_input;
pub mod textarea;
pub mod toggle;
pub mod tooltip;

pub mod prelude {
    // pub use crate::hero_icons::outlined::*;
    // pub use crate::hero_icons::solid::*;
    pub use crate::daisyui::alert::*;
    pub use crate::daisyui::avatar::*;
    pub use crate::daisyui::badge::*;
    pub use crate::daisyui::button::*;
    pub use crate::daisyui::card::*;
    pub use crate::daisyui::carousel::*;
    pub use crate::daisyui::collapse::*;
    pub use crate::daisyui::display_helper::*;
    pub use crate::daisyui::drawer::*;
    pub use crate::daisyui::dropdown::*;
    pub use crate::daisyui::home::*;
    pub use crate::daisyui::indicator::*;
    pub use crate::daisyui::link::*;
    pub use crate::daisyui::menu::*;
    pub use crate::daisyui::modal::*;
    pub use crate::daisyui::nav::*;
    pub use crate::daisyui::select::*;
    pub use crate::daisyui::step::*;
    pub use crate::daisyui::tab::*;
    pub use crate::daisyui::table::*;
    pub use crate::daisyui::text_input::*;
    pub use crate::daisyui::textarea::*;
    pub use crate::daisyui::toggle::*;
    pub use crate::daisyui::tooltip::*;
}
